services:
  webhook-server:
    build: .
    container_name: sasha-webhook-bitrixIKORA
    ports:
      - "${PORT:-3333}:${DOCKERPORT:-3333}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Монтируем код для разработки (можно закомментировать для продакшена)
      - ./server.js:/app/server.js:ro
      - ./mapping.js:/app/mapping.js:ro
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge
